version: "3"
services:
  eh2telegraph:
    image: ghcr.io/msknet/eh2telegraph:latest
    container_name: eh2telegraph
    restart: always
    network_mode: "host"
    environment:
      CONFIG_FILE: "/config.yaml"
      TZ: Asia/Shanghai
    volumes:
      - "./config.yaml:/config.yaml:ro"
    logging:
      driver: journald
