name: docker build and push

on:
  push:
    branches:
      - master

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: MSKNET
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/msknet/eh2telegraph:latest
